### ISSUE TITLE
Cannot extract messages from certain filetypes

### ISSUE THREAD

**Issue by dallyh** [opral/inlang-sherlock#12]
Hello, Sherlock does not seem to pick up some file types regarding extraction of messages in VSCode. The suggestions menu (light bulb / `crtl + .`) is empty for some of the file types I'm using. For example `.ts` files do get picked up and suggestions are populated with the `Inlang: Extract Message` entry, but in other files like `.astro` the entry is not in the suggestions menu.

Typescript file:
![image](https://github.com/opral/inlang-sherlock/assets/6968534/32b26da7-eb90-4c6d-a773-8d8bb3d3c0c4)

Astro file:
![image](https://github.com/opral/inlang-sherlock/assets/6968534/6b9c9916-3136-4348-9a1a-986c460fcbd1)

I don't know if this is an issue because `.astro` is a specific filetype for Astro framework, and it has it's own language server / vscode extension, or if it is just that some files are currently not supported. My guess is it's the former, because i18n-ally extension worked fine with key extraction.

**Comment by felixhaeberle** [comment]
@dallyh PR https://github.com/opral/monorepo/pull/2443

**Comment by felixhaeberle** [comment]
fixed with https://github.com/opral/monorepo/pull/2443
