### ISSUE TITLE
`m-function-matcher` only triggers when `import * as m` is found in the source file

### ISSUE THREAD

**Issue by GauBen** [opral/inlang-sherlock#127]
Hey!

I had a hard time figuring out why translation hints wouldn't show.

https://github.com/opral/monorepo/blob/4b9420b9bbeb2beb0e518c305130097500ddae12/inlang/source-code/plugins/m-function-matcher/src/ideExtension/messageReferenceMatchers.ts#L25C9-L25C43

I get why it is implemented this way, but for my use-case I have an i18n module that re-exports messages:

```ts
import { m, formatDate, formatTime } from '$i18n';
```

Would it be possible to relax `m-function-matcher` to allow any `m` import? Otherwise, I'd like to contribute an addition to the documentation for future reference.

**Comment by samuelstroschein** [comment]
Careful. The re-export likely breaks tree-shaking. You should check that in the build. Does the page that imports m from $i18n only containt the message that is used? 

If it doesn't break tree-shaking, we can evaluate the options. The risk are false positives e.g. something is an `m` variable that is not a message function.

**Comment by samuelstroschein** [comment]
In any case, contributions whether for the docs, or functionality are welcome. For the implementation, let's check tree-shaking first.

**Comment by GauBen** [comment]
Thanks for your swift reply @samuelstroschein! The `$i18n` module is "virtual", I'm using SvelteKit and I confirm that the build is properly tree-shaken, as there is no intermediate build step. I find the named import easier to use because VSCode can auto-add the import

**Comment by samuelstroschein** [comment]
Got it. Closing this issue in favor of https://github.com/opral/inlang-paraglide-js/issues/151. 

If you do a PR, I will accept and deploy it!
