### ISSUE TITLE
Increase Project-Detection Scan Depth

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-sherlock#13]
## Context/Problem

There is a limit to how deeply Sherlock scans to find inlang projects. In the monorepo the NextJS example projects are past that depth & can't interact with Sherlock. If we're having that problem it's a matter of time until someone else does too. 

## Proposal

Increase the limit by 2-3 levels or make it configurable

**Comment by samuelstroschein** [comment]
> or make it configurable

Please no. This will lead to diverging experiences in the ecosystem. 

I opened [LIX-43](https://linear.app/opral/issue/LIX-43/glob-function) with the goal to be fast enough to not require depth limits.

**Comment by felixhaeberle** [comment]
This is a SDK topic regarding listProjects, moving this to SDK.

**Comment by samuelstroschein** [comment]
non-issue with the sdk v2 anymore. the app needs to scan for themselves with a glob
