### ISSUE TITLE
integrate settings component into Sherlock 🕵️‍♂️

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-sherlock#14]
## Context/Problem

The overall functionality has been achieved internally, but not externally

## Proposal

Now make it available in the right spot, style it properly and make it publicly releasable

##

**Comment by NilsJacobsen** [comment]
I will work on the wording tomorrrow

**Comment by felixhaeberle** [comment]
The settings component is now fully integrated & styled into Sherlock and only waits on [INLMC-52](https://linear.app/opral/issue/INLMC-52/performance-issue-of-settings-component) to be released.
