### ISSUE TITLE
[bug] incorrect error message when sherlock preferred language is set to non-extant language

### ISSUE THREAD

**Issue by jldec** [opral/inlang-sherlock#15]
## Context/Problem

The preferred language causes spurious errors in projects which don't even have that language.
e.g. set preferred language to `de` and open project which only has `en`

You'll see errors like this:

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/02a8381b-7038-484a-8ed8-d0329598b05f/f5200baf-2854-4a1c-8edb-98173ec3c934?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wMmE4MzgxYi03MDM4LTQ4NGEtOGVkOC1kMDMyOTU5OGIwNWYvZjUyMDBiYWYtMjg1NC00YTFjLThlZGItOTgxNzNlYzNjOTM0IiwiaWF0IjoxNzEyMDY2MjA3LCJleHAiOjMzMjgyNjI2MjA3fQ.Jv3M7FF4PF36Jwfvq4JJkCN_MOoAVxP1ZjwouQ24u-g " alt="Screenshot 2024-04-02 at 14.54.12.png" width="991" height="195" />

## Proposal

1. warn users and ignore the preferred language if the project doesn't have that language.
2. fix the error to be correct about which language variant is actually missing.

**Comment by felixhaeberle** [comment]
👍 will fix!
