### ISSUE TITLE
next-intl t matcher not working

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sherlock#21]
<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/db73cf35-e06f-41d1-b2f4-f2133401513f/bfe1774f-c193-44f8-b78b-5a25e754bdf8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9kYjczY2YzNS1lMDZmLTQxZDEtYjJmNC1mMjEzMzQwMTUxM2YvYmZlMTc3NGYtYzE5My00NGY4LWI3OGItNWEyNWU3NTRiZGY4IiwiaWF0IjoxNzEzNDgwNTUyLCJleHAiOjMzMjg0MDQwNTUyfQ.10E3n5oK_BoJvXirY7rFMgGtmsqdkbOstfRRH7OdDko " alt="CleanShot 2024-04-18 at 18.48.51@2x.png" width="1150" height="2168" />

[https://discord.com/channels/897438559458430986/1230642655772414103/1230649882369331200](https://discord.com/channels/897438559458430986/1230642655772414103/1230649882369331200)

**Comment by calvinverso** [comment]
Commenting for follow-up and updates on the issue. As the other person in the screenshot above, I'm involved in this as well. Feel free to let me know if you have any further questions.

**Comment by NilsJacobsen** [comment]
Can you send me a schematic structure of your language resources, particularly for the example temporarilyUnavailable and are you using any namespaces?

**Comment by calvinverso** [comment]
the structure for that specific one is: 
`Form.checkout.temporarilyUnavailable`

fixed the pathPattern and the messages are now displaying in the sidebar
<img width="366" alt="Screenshot 2024-04-19 at 12 43 04 PM" src="https://github.com/opral/inlang-sherlock/assets/25255741/e2a58e6d-b66f-4f4c-8147-5b5a5cb53a86">

still getting the t-matcher error though
<img width="998" alt="Screenshot 2024-04-19 at 12 45 06 PM" src="https://github.com/opral/inlang-sherlock/assets/25255741/f9023d12-92c3-42f9-902d-23c16ece74f4">

**Comment by samuelstroschein** [comment]
@calvinverso this looks like a problem with namespacing. the message (`temporarilyUnavailable`) in the code can be matched with the key `Fom.checkout.temporarilyUnavailable`. 

Fixing this would require a dedicated next-intl matcher that detects namespaces. We'll probably do this but i suggest you to avoid this problem altogether by not using namespaces. 

Off-topic: We will introduce auto generated IDs for messages soon. There is no value in naming message keys, see https://inlang.com/documentation/concept/message#idhuman-readable

**Comment by calvinverso** [comment]
You're right, I tried not using namespaces and it worked. 
<img width="662" alt="image" src="https://github.com/opral/inlang-sherlock/assets/25255741/597bd4d4-ceeb-4c16-966a-7bc769318d8b">

Thank you for suggesting not using namespaces altogether, however, we will continue using them as the schematic structure is quite complex for most of the translations plus we have 100+ files and 1000+ messages where namespaces have already been implemented. 

Think we'll go on without using the matcher for now. Thanks for your support.

**Comment by samuelstroschein** [comment]
Sounds good. 

> 100+ files and 1000+ messages where namespaces have already been implemented. 

You have 100+ code files or 100+ translation files? If 100+ translation files, how do you send them to translators for translations? That sounds complicated

**Comment by calvinverso** [comment]
> You have 100+ code files or 100+ translation files? If 100+ translation files, how do you send them to translators for translations? That sounds complicated


100 code files

**Comment by felixhaeberle** [comment]
I'm going to close this as we don't want to spend optimize for namespaces here as we introduce human readable ids in the near future.

Also, 

> We will introduce auto generated IDs for messages soon. There is no value in naming message keys, see https://inlang.com/documentation/concept/message#idhuman-readable
