### ISSUE TITLE
open in fink link does not include branch

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sherlock#22]
### Problem

The open in fink link always opens the main branch even though I am locally in another branch.

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/d8f1d5e9-c1e3-44c6-bcd0-52fa44278fe5/be4050c1-3fa1-4fd0-96fb-39f315daa4d5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9kOGYxZDVlOS1jMWUzLTQ0YzYtYmNkMC01MmZhNDQyNzhmZTUvYmU0MDUwYzEtM2ZhMS00ZmQwLTk2ZmItMzlmMzE1ZGFhNGQ1IiwiaWF0IjoxNzEzODI2ODY3LCJleHAiOjMzMjg0Mzg2ODY3fQ.20Qy05Zul3QswGHrE9h0b_BAZHTksZZMP-OgtY_v0_0 " alt="CleanShot 2024-04-22 at 19.00.09@2x.png" width="928" height="442" />

### Proposal

Open the branch the dev is currently in.

**Comment by felixhaeberle** [comment]
@niklas.buchfink can you provide an ETA for this?

**Comment by NiklasBuchfink** [comment]
@felix.haeberle I put it on the list for this week

**Comment by NiklasBuchfink** [comment]
@felix.haeberle Wait, was it just about the fallback ([FINK-30](https://linear.app/opral/issue/FINK-30/add-fallback-for-not-existing-branches))?<br><br>If you link the branch correctly you can just add it to the url

**Comment by felixhaeberle** [comment]
Oh, to clarify: an error occurs in Fink if a local branch is not synced to remote. For non-existent branches, there should be a fallback to an existing branch.

**Comment by NiklasBuchfink** [comment]
@felix.haeberle I have merged the redirect/fallback: [FINK-30](https://linear.app/opral/issue/FINK-30/add-fallback-for-not-existing-branches)<br>You can now add the branch parameter to the url.
