### ISSUE TITLE
extract string with id as human id auto-filled

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-sherlock#23]
### Context

https://discord.com/channels/897438559458430986/1070750156644962434/1232511889527930962
Currently, there is no way for people to extract string with id as human id auto-filled.

### Proposal

Let people who have adopted human readable ids extract to it.
This issue is dependent on the persistence feature, which makes this possible.

**Comment by NilsJacobsen** [comment]
What do you mean by exporting?

**Comment by felixhaeberle** [comment]
this has already be accomplished and is already shipped in the live version of sherlock, but can be disabled with a settings.
