### ISSUE TITLE
Adding capability to generate message

### ISSUE THREAD

**Issue by ScreamZ** [opral/inlang-sherlock#35]
Hi,

Following your recommendation to report for wanted features compared to i18n ally,

I would like to be able to generate messages from keys, currently it's only possible if there is at least one item defined in one of the supported languages.

<img width="1698" alt="Screenshot 2024-05-07 at 13 10 43" src="https://github.com/opral/inlang-sherlock/assets/6640835/7c22420f-bc05-4d55-9b11-2f6f53103fef">

Here my inputPlaceholder key doesn't exist and I can't add it straight from here, I have to define it in the file JSON before.

**Comment by samuelstroschein** [comment]
@felix.haeberle this seems like a redundant feature once we ship human readable message bundle ids auto auto generate them in sherlock

**Comment by felixhaeberle** [comment]
@ScreamZ have you seen the **extract option** if you select a text and hit cmd + . or use the quick action liht bulb next to the selection?

**Comment by ScreamZ** [comment]
> @ScreamZ have you seen the **extract option** if you select a text and hit cmd + . or use the quick action liht bulb next to the selection? 

Nope, I missed it because I use to just put the cursor not select the whole key. Thanks 

Also it's bottom of suggestions (not part of quick fixes but part of more action)

**Comment by felixhaeberle** [comment]
Where would you add it? Would it be good to have a "Create message" / "Extract message" in the command palette?

**Comment by jldec** [comment]
+1 for command palette 🙏
