### ISSUE TITLE
Add machine translations to context menu

### ISSUE THREAD

**Issue by ScreamZ** [opral/inlang-sherlock#36]
In i18n ally, I'm able to translate directly from my source lang to others using deepl or google translate from this contextual menu, it could be nice to have this feature too.

![Screenshot 2024-05-07 at 13 13 43](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/57db3468-9c4e-4e06-8a7c-6f260740470a/f6ca675c-f37f-4e56-87e1-ddf87654863d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC81N2RiMzQ2OC05YzRlLTRlMDYtOGE3Yy02ZjI2MDc0MDQ3MGEvZjZjYTY3NWMtZjM3Zi00ZTU2LTg3ZTEtZGRmODc2NTQ4NjNkIiwiaWF0IjoxNzE1MDgxNDQ2LCJleHAiOjMzMjg1NjQxNDQ2fQ.um4I4wrZciphqCkxRyEio92qkKVbfzeW2gX3CSycFAI "=360x")

**Comment by felixhaeberle** [comment]
Thank you for the feature request. We already offer machine translate through the inlang CLI: [https://inlang.com/m/2qj2w8pu/app-inlang-cli](https://inlang.com/m/2qj2w8pu/app-inlang-cli) – we also offer translations through the message view in the sherlock tab. Just click "translate" icon next to the empty message.<br><br>We will add this feature also to the context menu 👍
