### ISSUE TITLE
add supported i18n libraries to product page

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sherlock#45]
### Context

I was recommending sherlock \[here\]([https://www.reddit.com/r/react/comments/tl1zjz/comment/l4b4zfj/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](https://www.reddit.com/r/react/comments/tl1zjz/comment/l4b4zfj/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)) and saw that the product page doens't list the supported i18n libraries.

### Proposal

Add a "supported i18n libraries" section to the product pages that links to the plugins, similar to what @loris.sigrist did with the "tooling" section in paraglide js.

![CleanShot 2024-05-16 at 10.18.58@2x.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/eb502d04-ad88-4ce9-a3d4-851b438bd051/572ae824-c39a-46d2-b9bd-ed08d681f4a0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9lYjUwMmQwNC1hZDg4LTRjZTktYTNkNC04NTFiNDM4YmQwNTEvNTcyYWU4MjQtYzM5YS00NmQyLWI5YmQtZWQwOGQ2ODFmNGEwIiwiaWF0IjoxNzE1ODY5MjI4LCJleHAiOjMzMjg2NDI5MjI4fQ.ju32nNIhtQo_Y30GBWvtsDJNPBNd6yVWsT63X4ysEEw "=1064x")

![CleanShot 2024-05-16 at 10.15.38@2x.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/d48acabb-2de9-4911-ac3b-a45e5470f52d/aa849efa-25ee-4af6-a3b3-caaadd001b6d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9kNDhhY2FiYi0yZGU5LTQ5MTEtYWMzYi1hNDVlNTQ3MGY1MmQvYWE4NDllZmEtMjVlZS00YWY2LWEzYjMtY2FhYWRkMDAxYjZkIiwiaWF0IjoxNzE1ODY5MjI4LCJleHAiOjMzMjg2NDI5MjI4fQ.m3Zi0xdCVST9skFAXXBDqs_tRYjB5Cory3Z-91guLGk "=1824x")

**Comment by felixhaeberle** [comment]
In general, we support much more than the ones you listed. 

E.g. people already using it with React Native with the t function matcher & JSON plugin. 

I though we went against generally optimizing the communication for JS libs, but it could help for people to "verify" & adopt faster 👍 

Lets try this out.
