### ISSUE TITLE
VSCode warning: "The message ID 'myNamespace:translationKey' is not a valid javascript identifier"

### ISSUE THREAD

**Issue by billomore** [opral/inlang-sherlock#50]
Hi, thanks for the great extension!

Just one strange quirk: when I enable the extension, VSCode starts complaining on each instance of the `t` function call; it says "[myNamespace:translationKey] - The message ID 'myNamespace:translationKey' is not a valid javascript identifier". Sample code looks like this:
```typescript
import { useTranslation } from 'react-i18next';

const MyComponent = () => {
  const { t } = useTranslation('myNamespace');
  const translatedString = t('translationKey'); // <--- warning here
}
```

The code works fine, all the other extension functionality too - it adds the translation to the `t` call, shows all the messages in the sidebar - flawless.  But now my translation-heavy components are all yellow with ugly numbers :) When I disable the extension the error disappears, but it's very, very nice and I'm battling the OCD to use it :D

**Comment by samuelstroschein** [comment]
> The message ID 'myNamespace:translationKey' is not a valid javascript identifier".

Remove the valid js identifier lint rule from your settings file [https://inlang.com/m/teldgniy/messageLintRule-inlang-validJsIdentifier](https://inlang.com/m/teldgniy/messageLintRule-inlang-validJsIdentifier)

**Comment by samuelstroschein** [comment]
i removed the lint rule from the default installed lint rules https://github.com/opral/monorepo/commit/a61b4d914417bc40e057cb4378723f6a1b0cb122

**Comment by billomore** [comment]
thank you :)
