### ISSUE TITLE
Inline translations show error with aliases

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-sherlock#53]
* When using the monorepo website project the keys are not resolved correctly anymore
* The translations on the page are also not shown on the left

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/8e122b77-7d4e-42cc-a917-711ff66bcc5d/5a24d877-f550-4910-a071-2d4b9a70c364?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC84ZTEyMmI3Ny03ZDRlLTQyY2MtYTkxNy03MTFmZjY2YmNjNWQvNWEyNGQ4NzctZjU1MC00OTEwLWEwNzEtMmQ0YjlhNzBjMzY0IiwiaWF0IjoxNzE2OTY0Njg1LCJleHAiOjMzMjg3NTI0Njg1fQ.WzjPfOHZvF8GfEmfuZ37FyeO39rGokQgIdTHV2aqoKQ " alt="image.png" width="1170" height="947" />

Do we have a setup problem here?

**Comment by felixhaeberle** [comment]
@nils.jacobsen what does the error view say beneath the messages view. Have you tried reloading the extension?

**Comment by felixhaeberle** [comment]
cc @jldec This happens when the experimental alias flag is set to true. As I can remember, we talked about this one before. Is there a way we can enable both the alias & the human id for the matcher? (this worked before as I remember).<br><br>@nils.jacobsen Temporarily remove the experimental alias flag or set it to false.

**Comment by NilsJacobsen** [comment]
@felix.haeberle it says `No errors found`

**Comment by NilsJacobsen** [comment]
ahh I see.

**Comment by jldec** [comment]
I'll investigate - assigned to me.

**Comment by jldec** [comment]
This is the same issue as [MESDK-94](https://linear.app/opral/issue/MESDK-94/querymessagesgetbydefaultalias-not-working-in-sherlock-inline)
