### ISSUE TITLE
"ERROR: … not found in source with" when using translations with different namespaces in the same file.

### ISSUE THREAD

**Issue by typeofweb** [opral/inlang-sherlock#56]
# Environment
- next.js@15.0.0-canary-1
- next-intl@3.14.1

# `project.inlang/settings.json`

```json
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": ["en", "de"],
	"modules": ["https://cdn.jsdelivr.net/npm/@inlang/plugin-next-intl@latest/dist/index.js"],
	"plugin.inlang.nextIntl": {
		"pathPattern": "./messages/{languageTag}.json"
	}
}
```

# Code
```tsx
import { getTranslations } from "next-intl/server";

export const C1 = async () => {
	const t = await getTranslations("/cart");
	return t("empty.title");
};
export const C2 = async () => {
	const t = await getTranslations("/product");
	return t("page.imagesTitle");
};
```

# Result
There's an error reported on line `t("page.imagesTitle")` "ERROR: … not found in source with" even though the invocation is correct and works.

**Comment by felixhaeberle** [comment]
@typeofweb Hi, thanks for opening the issue.

I currently do not understand what you are doing with the argument of `/chart` & `/product`. 

According to the docs, this is not a "Link field", but a regular string.
https://next-intl-docs.vercel.app/docs/environments/server-client-components#async-components

Regardless, if your key is then also `/cart.empty.title` or `/product.page.imagesTitle` this should work.

But I'm assuming in your language file, this is just `cart` or `product`.

**Comment by typeofweb** [comment]
Here's my language file (simplified):

```json
{
	"/product": {
		"page": {
			"imagesTitle": "Images"
		}
	},
	"/cart": {
		"empty": {
			"title": "Your cart is empty"
		}
	}
}
```

**Comment by felixhaeberle** [comment]
Sorry for closing too early! I see. The second hook namespace isn't properly addressed to the respective t function. Let me inspect this real quick.

**Comment by felixhaeberle** [comment]
fix in https://github.com/opral/monorepo/pull/2858
