### ISSUE TITLE
creating a project reloads workspace

### ISSUE THREAD

**Issue by KraXen72** [opral/inlang-sherlock#58]
clicking the create project button in the sherlock extension reloaded the entire vs code workspace for me, killing any running cli scripts in the embedded terminal - luckily, it wasn't anything important, but it could have bad consequences.

if possible, remove the requriement of a full workspace reload. alternatively, add a warning before doing it with a confirmation dialog for the user.

Thanks!

**Comment by felixhaeberle** [comment]
Thank you for opening this issue! We're looking into it and see where we can improve the experience.
