### ISSUE TITLE
rename vs-code-extension package to @inlang/sherlock

### ISSUE THREAD

**Issue by jldec** [opral/inlang-sherlock#59]
### Context

The name `vs-code-extension` is hard to remember.

I use a bash function to launch dev servers, run builds, tests etc, and it would help if package names were consistent (all start with @inlang/) even those which are not published to npm. Currently this function works for @inlang/\* packages, but not for sherlock. E.g. I can do `dp sdk test` or `dp cli… build` which I find quite useful.

```
dp () 
{ 
    pushd ~/opral/monorepo && doppler run --fallback-only -- pnpm --filter @inlang/$@ && popd
}
```

### Proposal

call it @inlang/sherlock

**Comment by samuelstroschein** [comment]
we can't use a `@inlang/*` namespace because vscode doesn't allow publishing with namespaces (at least that was the status 1 year ago)
