### ISSUE TITLE
"debug vs-code-extension" does not work anymore

### ISSUE THREAD

**Issue by jldec** [opral/inlang-sherlock#63]
### Context

I used to be able to debug sherlock code with the `debug vs-code-extension` config, but this is no longer working for me.

The 2nd window with the debug project workspace appears as before, but any breakpoints e.g. in inlang/source-code/ide-extension/src/main.ts are ignored and remain grey.

This is blocking investigation of [SHERL-57](https://linear.app/opral/issue/SHERL-57/inline-translations-show-error-with-aliases) 

### Proposal

**Comment by felixhaeberle** [comment]
fix in [https://github.com/opral/monorepo/commit/4a61e9162c13623f5df4fbf3e6a1fad88c9d84de](https://github.com/opral/monorepo/commit/4a61e9162c13623f5df4fbf3e6a1fad88c9d84de)
