### ISSUE TITLE
IDE Extension doesn't react when new project is created

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-sherlock#7]
## Problem 

Currently the IDE extension does not pick up on a new project being created. You need to reload the window to re-scan after creating a project, with, for example, `paraglide-js init`. This is easy to forget & can cause frustration

## Proposal
Add a few default watch-locations for new projects and react when one is created.

**Comment by samuelstroschein** [comment]
trying to see if comments still appear on linear
