### ISSUE TITLE
ship default human ids in sherlock already

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sherlock#75]
### Context

We can avoid discussions like [https://discord.com/channels/897438559458430986/1247937929876082839/1248258473851093054](https://discord.com/channels/897438559458430986/1247937929876082839/1248258473851093054) and substantially improve the UX of extracting messages already by shipping human ids in sherlock on extraction before importers/exporters arrive.

### Proposal

Ship default filled in human ids in sherlock now to:

* avoid discussions around naming keys for greenfield paraglide projects
* increase the UX of sherlock (coming up with names is so frustrating!)

![CleanShot 2024-06-06 at 08.58.16@2x.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/bb5c3f84-ffff-4c1b-b1ff-e4f91ba4ce91/ab813c19-f20e-4336-9780-dc7a54f4d297?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iYjVjM2Y4NC1mZmZmLTRjMWItYjFmZi1lNGY5MWJhNGNlOTEvYWI4MTNjMTktZjIwZS00MzM2LTk3ODAtZGM3YTU0ZjRkMjk3IiwiaWF0IjoxNzE3Njc4ODk2LCJleHAiOjMzMjg4MjM4ODk2fQ.NzRSFsjxe3RcRjv9AeviAqOarf4wioQlpUwPawZu4Xw "=1368x")

### Scenarios

BEST CASE:

The human ids sherlock uses will be the human ids that the SDK uses which means no aliases will be used once importer/exporter ships

WORST CASE:

The human ids differ from the importer/exporter ids the SDK will use. In that case, the human ids will be treated as aliases. AKA Status quo. Still a better UX for sherlock and paraglide users in the meantime.

**Comment by samuelstroschein** [comment]
@martin.lysk1 @jldec is a human id generator function exposed by the sdk?

```
const id = generateMessageBundleId()  
```

**Comment by martin-lysk** [comment]
Yes this should do the trick:

[https://github.com/opral/monorepo/blob/fb731c9c25958a8df089c636217fbb7916bdddbd/inlang/source-code/sdk/src/storage/human-id/human-readable-id.ts#L5](https://github.com/opral/monorepo/blob/fb731c9c25958a8df089c636217fbb7916bdddbd/inlang/source-code/sdk/src/storage/human-id/human-readable-id.ts#L5)

**Comment by felixhaeberle** [comment]
I will enable this for the experimental usage of human readable ids.

**Comment by samuelstroschein** [comment]
> I will enable this for the experimental usage of human readable ids.

the proposal is explicitly to enable this now for everyone. we don't have to wait for sdk features. 

were you confused by the proposal or have concerns about enabling this now for everyone?

**Comment by samuelstroschein** [comment]
> We could check if the id is a human id (each word is known) already and don't create an alias?!

Yes, that's what I had in mind with this proposal. <br><br>(Back when we discussed introducing human ids 8-12 weeks ago, I was not aware how long it would take. So, I'd say now ship it in sherlock and be aware in [MESDK-66](https://linear.app/opral/issue/MESDK-66/importerexporter-project-discussion) that messages that obey to a human readable id should not be imported as alias)

**Comment by felixhaeberle** [comment]
> were you confused by the proposal or have concerns about enabling this now for everyone?

<br>This would hurt the vast majority of users (like everybody right now) who have other naming systems. Providing them with this wrong default (in their case) would dramatically reduce DX & lead to inconsistent key naming which they gonna try to avoid. <br><br>"Of course, they don't have to accept this default" you might say, but this really feels like the wrong thing to do from Sherlock staying unopinionated about keystyles.<br><br>Results: Lots of open issues & bugs where people request other defaults or options. <br><br>Worst: User switches to other solution which is unopinionated about keystyle.

**Comment by samuelstroschein** [comment]
> This would hurt the vast majority of users (like everybody right now) who have other naming systems.

I heavily doubt this. Can you ship this feature and if users complain deactivate it again? <br><br>We are running into endless discussions with naming things. Just ship this.

**Comment by jldec** [comment]
fyi randomHumanId() is now exported on the @inlang/sdk api.<br>[https://github.com/opral/monorepo/pull/2930](https://github.com/opral/monorepo/pull/2930)

**Comment by samuelstroschein** [comment]
@felix.haeberle are you gonna ship this?

**Comment by felixhaeberle** [comment]
yes, its [on my list for today](https://discord.com/channels/897438559458430986/1084748995349446667/1252113659761659924).

**Comment by felixhaeberle** [comment]
@samuel.stroschein Satisfied? 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/a3164130-4fc8-4abc-aee1-a5f286bb0e95/44502e6b-eeff-47d7-a01d-2f1438fcfcd0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9hMzE2NDEzMC00ZmM4LTRhYmMtYWVlMS1hNWYyODZiYjBlOTUvNDQ1MDJlNmItZWVmZi00N2Q3LWEwMWQtMmYxNDM4ZmNmY2QwIiwiaWF0IjoxNzE4NjI3NDY1LCJleHAiOjMzMjg5MTg3NDY1fQ.QaIYoZ64uNZgu9k1X8Hp9-Mv-R0DIpE-7kwbgiVwUk8 " alt="Bildschirmfoto 2024-06-17 um 14.25.41.png" width="632" height="137" />

<br><br>I can't change the Enter/Escape part.<br><br>I haven't done any opt-in / opt-out behavior as of now. Will do that with the first complain (100% sure about people will complain and want this to be modified) – thought about `sherlock.extract.autoHumanId` which defaults to `true` but can be set to `false`.

**Comment by samuelstroschein** [comment]
> I haven't done any opt-in / opt-out behavior as of now

I don't think it will be needed.

**Comment by samuelstroschein** [comment]
yes, baba let's goooo!

**Comment by jldec** [comment]
👶 🚀
