### ISSUE TITLE
Eslint & sherlock

### ISSUE THREAD

**Issue by benjaminpreiss** [opral/inlang-sherlock#8]
When strings are entered and then marked to extract them with sherlock it can happen that sherlock extracts the parentheses as well.
I assume it has something to do with sherlock and eslint working at the same time and eslint converting e.g. `"` to `'`.

**Comment by benjaminpreiss** [comment]
My eslint config will convert `"` to `'`.

When I mark a string that uses `"` and extract it, sometimes the parentheses are extracted as well.

Immediately before extraction:

<img width="683" alt="Screenshot 2024-03-14 at 17 46 23" src="https://github.com/opral/inlang-sherlock/assets/28349122/d7e02fd1-5dd6-4534-8916-a04c8972c851">

After extraction:

<img width="683" alt="Screenshot 2024-03-14 at 17 46 45" src="https://github.com/opral/inlang-sherlock/assets/28349122/80cd1342-1ee6-42ef-8268-6a9d14f98898">

Then, when I check out the messages, sometimes I can see a `'` in there.

**Comment by benjaminpreiss** [comment]
found an example on how this get's extracted:

<img width="476" alt="Screenshot 2024-03-14 at 17 57 31" src="https://github.com/opral/inlang-sherlock/assets/28349122/cc8ef7fd-250b-4ff8-bcbc-5609aae2c055">

**Comment by felixhaeberle** [comment]
hey @benjaminpreiss – we use quote stripping. 

see https://github.com/opral/monorepo/blob/bbedec5c6c4d2bb024b9b241475c444a6e5dc847/inlang/source-code/ide-extension/src/commands/extractMessage.ts#L53

and 

https://github.com/opral/monorepo/blob/bbedec5c6c4d2bb024b9b241475c444a6e5dc847/inlang/source-code/ide-extension/src/utilities/messages/isQuoted.ts#L1-L8

**Comment by felixhaeberle** [comment]
@samuelstroschein sad, we don't get code previews now anymore

**Comment by felixhaeberle** [comment]
@benjaminpreiss we use quote stripping

https://github.com/opral/monorepo/blob/658e3234235e7984325cebe344ddf06020720757/inlang/source-code/ide-extension/src/commands/extractMessage.ts#L53

**Comment by felixhaeberle** [comment]
@benjaminpreiss is this answering your question?

**Comment by felixhaeberle** [comment]
@benjaminpreiss any update on this?

**Comment by benjaminpreiss** [comment]
Yes, I think it does - also, just a minor problem on my side
