### ISSUE TITLE
Misleading error in Sherlock when language setting is set to non-source language, and the message translation is missing for that language

### ISSUE THREAD

**Issue by jldec** [opral/inlang-sherlock#82]
### Context

See below, when sherlock is set to show de, and the string is missing in de, it says "… not found in source with language tag 'en' "

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/71677948-b328-4a0b-80d8-df8a454bd697/50decdd4-2610-4b9f-8456-408ba53f4053?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC83MTY3Nzk0OC1iMzI4LTRhMGItODBkOC1kZjhhNDU0YmQ2OTcvNTBkZWNkZDQtMjYxMC00YjlmLTg0NTYtNDA4YmE1M2Y0MDUzIiwiaWF0IjoxNzE4NzA2MTI3LCJleHAiOjMzMjg5MjY2MTI3fQ.bAkQwwTOClScqgEmrT2Dkh_wBXrl2NI-jBN0NpKoLSs " alt="Screenshot 2024-06-18 at 11.16.38.png" width="1206" height="218" />

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/578c9c81-6278-4b38-9585-2800d02d1b02/bfca9462-7441-4242-8fb4-be3b211d216f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC81NzhjOWM4MS02Mjc4LTRiMzgtOTU4NS0yODAwZDAyZDFiMDIvYmZjYTk0NjItNzQ0MS00MjQyLThmYjQtYmUzYjIxMWQyMTZmIiwiaWF0IjoxNzE4NzA2MTI3LCJleHAiOjMzMjg5MjY2MTI3fQ.4lIhsRfG01_PuyXnTP9WFxIvb6E2gcdGTUTGN6b31i4 " alt="Screenshot 2024-06-18 at 11.16.22.png" width="1246" height="280" />

### Proposal

it should say "… not found in source with language tag 'de' "

**Comment by felixhaeberle** [comment]
@jldec Haven't we fixed this before? I will look into it.

**Comment by jldec** [comment]
yeah, I thought it was fixed too, so that's why I was a bit surprised to see this
