### ISSUE TITLE
Sherlock VSCode extension cant detect project on multi-project workspace.

### ISSUE THREAD

**Issue by jorgev259** [opral/inlang-sherlock#85]
Sherlock tab doesnt show the project and prompts me to create one when it already exists. If i open the project outside of the workspace Sherlock works correctly.

- hey, do you have errors in the debug console?
No errors

- is there any limitation on writing to the filesystem from your machine? 
No

- which versions of sherlock are you using?
1.48.3   

- can you share you project.inlang/settings.json ?
Workspace looks like this. Only soc_site-astro uses Paraglide.
![imagen](https://github.com/user-attachments/assets/472b369e-066f-4579-b5be-343b5cdcdfd2)
```json
{
  "$schema": "https://inlang.com/schema/project-settings",
  "sourceLanguageTag": "en",
  "languageTags": [
    "en"
  ],
  "modules": [
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js"
  ],
  "plugin.inlang.messageFormat": {
    "pathPattern": "./messages/{languageTag}.json"
  }
}
```

- have you tried updating sherlock & vscode & restart your workspace?
Yes

- if you visit the sherlock tab in the sidebar, how does it look like?
![imagen](https://github.com/user-attachments/assets/205a5a1c-68a2-4fdc-9eb2-1b4e11665178)
Also when extracting a message, the following error shows up
![imagen](https://github.com/user-attachments/assets/13a2301a-810b-4aaa-a7fa-1f4b96d3737e)

**Comment by felixhaeberle** [comment]
This is expected because Sherlock is only looking in folders beneath  the opened workspace folder. You should wrap your projects in one monorepo then and open that one.

**Comment by Yuniac** [comment]
This just happened to me too in vscode too. 

To fix this, make sure the repo that have the `yourprojectname.lang` folder is the top/first one in the `Explorer` tab, you can drag and drop the open folders to re-organize them.
