### ISSUE TITLE
render alias next to message id in message tab

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-sherlock#9]
## Problem
No aliases are being shown.
<img width="324" alt="Bildschirmfoto 2024-03-18 um 00 21 10" src="https://github.com/opral/inlang-sherlock/assets/34959078/4bd08d5b-b174-4b12-85ad-1f93c1a8b631">

## Proposal
- provide a way for people to still observe/see their aliases even when they are using human id's
- incorporate in the design that aliases could be editable in the future for platform specific keys/aliases & more

**Comment by NilsJacobsen** [comment]
Nice update. I like the positioning under the list of languages. 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/c1e8513b-fbcf-45a9-9fc2-b0c37bfd6e14/31f1f3dd-768a-4ae4-900f-cc0372b02b02?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9jMWU4NTEzYi1mYmNmLTQ1YTktOWZjMi1iMGMzN2JmZDZlMTQvMzFmMWYzZGQtNzY4YS00YWU0LTkwMGYtY2MwMzcyYjAyYjAyIiwiaWF0IjoxNzEwNzQ3OTkwLCJleHAiOjMzMjgxMzA3OTkwfQ.WTdl5vH5NWcx4k98OvqiQlqm5o0kbWExlnV9QlqY6uM " alt="image.png" width="595" height="421" />

Minor thing: I would shift the '@default …' text to the right so it aligns to the languageTags. That way you have a clear separation from the next id.
