### ISSUE TITLE
create utility functions for most used lint rules

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-sherlock#93]
### Context

We decided to not ship lint rules anymore in the inlang SDK because they belong to lix now, as lix validation rules. In the meantime, we create utility functions which query and process the messages in a form a lint rule would do, to replace the existing behavior.

See:

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/e773758b-43f0-4acc-8bce-648a7485c380/da72b1e4-ac69-46fa-a8f5-8af30c5ac9da?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9lNzczNzU4Yi00M2YwLTRhY2MtOGJjZS02NDhhNzQ4NWMzODAvZGE3MmIxZTQtYWM2OS00NmZhLWE4ZjUtOGFmMzBjNWFjOWRhIiwiaWF0IjoxNzI1OTcxOTYwLCJleHAiOjMzMjk2NTMxOTYwfQ.ICvIWnNBmeqJX4CYweJH4Oscq2JPchFEKFcgbqyBriQ " alt="CleanShot_2024-09-05_at_16.46.552x.png" width="1130" height="876" />

### Proposal

Lint rules which have high bandwidth and therefore need to be replaced:

- [ ] missingTranslation
- [ ] messageWithoutSource
- [ ] emptyPattern
- [ ] validJsIdentifier

**Comment by samuelstroschein** [comment]
valid js identifier is not needed anymore. paraglide uses internal ids to compile and typescript now allows invalid js identifiers
