### ISSUE TITLE
integrate lint rules in vscode diagnostics & inline display feature

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-sherlock#96]
integrate lint rules in vscode diagnostics & inline display feature – but only show them when they are mentioned in the settings modules for the project.

**Comment by felixhaeberle** [comment]
No, just today we had a user who was annoyed by the display of a certain lint rule. I will make them conditonal.

**Comment by samuelstroschein** [comment]
i would add a setting in sherlock. every imported lint rule leads to a warning "deprecated lint rule" and the user was not able to deactivate a lint rule because the modules array is not obvious

**Comment by felixhaeberle** [comment]
Adding settings in Sherlock is not trivial, you have to exclusively distribute & migrate / remove them by maintaining the same behavior if we change to another system in 30-60 days.

**Comment by samuelstroschein** [comment]
@felix.haeberle use `settings['app.sherlock']`
